# Generated by Django 4.1.5 on 2023-02-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deprem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olus_zamani', models.DateTimeField(verbose_name='Tarih-Saat')),
                ('enlem', models.CharField(max_length=7, verbose_name='Enlem')),
                ('boylam', models.CharField(max_length=7, verbose_name='Boylam')),
                ('derinlik', models.FloatField(verbose_name='Derinlik (km)')),
                ('buyukluk', models.FloatField(verbose_name='Büyüklük')),
                ('yer', models.CharField(max_length=200, verbose_name='Yer')),
            ],
        ),
    ]
