# Generated by Django 4.1.5 on 2023-02-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorimodel',
            name='kategori',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
