# Generated by Django 4.1.5 on 2023-02-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0002_alter_kategorimodel_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersmodel',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori_iliski', to='dersler.kategorimodel'),
        ),
        migrations.AlterField(
            model_name='dersmodel',
            name='resim',
            field=models.ImageField(upload_to='', verbose_name=''),
        ),
    ]
