# Generated by Django 4.1.5 on 2023-02-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0003_alter_dersmodel_kategori_alter_dersmodel_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dersmodel',
            name='resim',
        ),
        migrations.AlterField(
            model_name='dersmodel',
            name='son_duzenleme',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Son Düzenlenme Tarihi'),
        ),
    ]
