# Generated by Django 4.1.5 on 2023-02-05 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dersler', '0004_remove_dersmodel_resim_alter_dersmodel_son_duzenleme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersmodel',
            name='yazar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to=settings.AUTH_USER_MODEL),
        ),
    ]
