# Generated by Django 4.1.5 on 2023-02-05 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dersler', '0005_alter_dersmodel_yazar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersmodel',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_kategori', to='dersler.kategorimodel'),
        ),
        migrations.AlterField(
            model_name='dersmodel',
            name='yazar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici', to=settings.AUTH_USER_MODEL),
        ),
    ]
